version: '3.4'

services:
  postgresql_database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=strongman_bot
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - database:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@postgres.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - '5050:80'
    restart: always
    volumes:
      - pgadmin:/root/.pgadmin

volumes:
  database:
  pgadmin: